# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-UVVQwW5L1-wYbBlhp2JBEz8U0cPqgRt

Datamining : Histogram / Scatterplot
"""

import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn-white')
data = np.random.randn(1000)
plt.hist(data);
plt.hist(data,bins=20,alpha=0.5,histtype='stepfilled',color='steelblue',edgecolor='none');

plt.style.use('seaborn-whitegrid')
x = np.linspace(0,10,30)
y=np.sin(x)
plt.plot(x,y,'o',color='black');

from sklearn.datasets import load_iris
iris = load_iris()
features = iris.data.T
plt.scatter(features[0],features[1],alpha=0.2,s=100*features[3],c=iris.target,cmap='viridis')
plt.xlabel(iris.feature_names[0])
plt.ylabel(iris.feature_names[1]);

